ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "authId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "displayName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE "User" ALTER COLUMN "username" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "User_authId_key" ON "User"("authId");
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");
