ALTER TABLE "Conversation"
ADD COLUMN IF NOT EXISTS "sessionMeta" JSONB;

ALTER TABLE "ScenarioAttempt"
ADD COLUMN IF NOT EXISTS "hintsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "hintPenaltyScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "hintPenaltyXp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "rawOverallScore" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "adjustedOverallScore" DOUBLE PRECISION;
